[build]
functions = ".netlify/functions"
publish = "."

[functions]
node_bundler = "esbuild"

[build]
  publish = "." # O el directorio donde está tu archivo HTML principal
  functions = ""netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/functions/:splat"
  status = 200
